export const ROLES = {
    USER: "USER",
    STAFF: "STAFF",
};
export const ORDER_STATUS = {
    PROCESSING: "PROCESSING",
    CONFIRMED: "CONFIRMED",
    DISPATCHED: "DISPATCHED",
    DELIVERING: "DELIVERING",
    DELIVERED: "DELIVERED",
    CANCELLED: "CANCELLED",
    REFUNDED: "REFUNDED"
};
export const PAYMENT_METHOD = {
    CASH_ON_DELIVERY: "CASH_ON_DELIVERY",
    BANK_TRANSFER: "BANK_TRANSFER",
    VOUCHER: "VOUCHER",
    MOBILE_BANKING: "MOBILE_BANKING"
};